# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:ios)


before_all do
  if is_ci
    setup_ci()
  end
end


desc "Installs all Certs and Profiles necessary for ad-hoc"
lane :match_me do
  match(
    type: "adhoc",
    app_identifier: [
        "io.getstream.reactnative.slackclone",
    ],
    readonly: true,
    force_for_new_devices: !is_ci
  )
end

platform :ios do
  desc "Deploy iOS build to Firebase"
  lane :deploy_to_firebase do
      match_me

      settings_to_override = {
        :BUNDLE_IDENTIFIER => "io.getstream.reactnative.imessageclone",
        :PROVISIONING_PROFILE_SPECIFIER => "match AdHoc io.getstream.reactnative.imessageclone"
      } 

      package = load_json(json_path: "./package.json")
      increment_version_number(
        version_number: package["version"],
        xcodeproj: "./ios/SlackCloneReactNative.xcodeproj"
      )

      increment_build_number(
        xcodeproj:"./ios/SlackCloneReactNative.xcodeproj"
      )

      gym(
          workspace: "./ios/SlackCloneReactNative.xcworkspace",
          scheme: "SlackCloneReactNative",
          export_method: "ad-hoc",
          export_options: "./fastlane/beta_gym_export_options.plist",
          silent: true,
          clean: true,
          xcargs: settings_to_override,
          include_symbols: true,
          output_directory: "./dist",
      )

      firebase_app_distribution(
        app: "1:296557120037:ios:c96ba73046f424b8f60dcc",
        groups: "react-native-dev",
      )
  end
end

platform :android do
  desc "Deploy Android build to Firebase"
  lane :deploy_to_firebase do
      increment_version_code(
        gradle_file_path:"./android/app/build.gradle"
      )
      package = load_json(json_path: "./package.json")
      increment_version_name(
        gradle_file_path:"./android/app/build.gradle",
        version_name: package["version"]
      )
      gradle(
        project_dir: "./android",
        tasks: ["clean", "assembleRelease"]
      )
      firebase_app_distribution(
          app: "1:296557120037:android:13ccb281a7750765f60dcc",
          android_artifact_type: "APK",
          android_artifact_path: "./android/app/build/outputs/apk/release/app-release.apk",
          groups: "react-native-dev"
      )
  end
end
