import { generateRandomId } from "stream-chat-expo";

const assetsDirectory =
  "/Users/enigma/react_native/react-native-samples/projects/twitchCloneExpo/assets";

const gifAssest = ({ name }: { name: string }): string => {
  return `${assetsDirectory}/gifs/${name}.gif`;
};

const emoteAsset = ({ name }: { name: string }): string => {
  return `${assetsDirectory}/emotes/${name}.png`;
};

export const emoticons = [
  // Gifs
  { image: gifAssest({ name: "aaugh" }), tag: "aaugh" },
  { image: gifAssest({ name: "ayayajam" }), tag: "ayayajam" },
  { image: gifAssest({ name: "balddab" }), tag: "balddab" },
  { image: gifAssest({ name: "baldflick" }), tag: "baldflick" },
  { image: emoteAsset({ name: "notsquishy" }), tag: "notsquishy" },
  { image: emoteAsset({ name: "poledoge" }), tag: "poledoge" },
  { image: emoteAsset({ name: "rarepepe" }), tag: "rarepepe" },
  { image: emoteAsset({ name: "ronsmug" }), tag: "ronsmug" },
  { image: emoteAsset({ name: "saltycorn" }), tag: "saltycorn" },
  { image: emoteAsset({ name: "m&mjc" }), tag: "m&mjc" },
  { image: gifAssest({ name: "baldfloss" }), tag: "baldfloss" },
  { image: gifAssest({ name: "baldspin" }), tag: "baldspin" },
  { image: gifAssest({ name: "baldyappp" }), tag: "baldyappp" },
  { image: gifAssest({ name: "baldyikes" }), tag: "baldyikes" },
  { image: emoteAsset({ name: "kappscool" }), tag: "kappscool" },
  { image: emoteAsset({ name: "karappa" }), tag: "karappa" },
  { image: emoteAsset({ name: "kkona" }), tag: "kkona" },
  { image: emoteAsset({ name: "hhhehehe" }), tag: "hhhehehe" },
  { image: emoteAsset({ name: "lul" }), tag: "lul" },
  { image: gifAssest({ name: "baners" }), tag: "baners" },
  { image: gifAssest({ name: "bropls" }), tag: "bropls" },
  { image: gifAssest({ name: "catjam" }), tag: "catjam" },
  { image: gifAssest({ name: "checkers" }), tag: "checkers" },
  { image: gifAssest({ name: "click" }), tag: "click" },

  { image: gifAssest({ name: "coomtime" }), tag: "coomtime" },
  { image: gifAssest({ name: "crawlers" }), tag: "crawlers" },
  { image: gifAssest({ name: "deadlole" }), tag: "deadlole" },
  { image: gifAssest({ name: "deskchan" }), tag: "deskchan" },
  { image: gifAssest({ name: "eato" }), tag: "eato" },

  { image: gifAssest({ name: "eddiebaldmansmash" }), tag: "eddiebaldmansmash" },
  { image: gifAssest({ name: "eddieknead" }), tag: "eddieknead" },
  { image: gifAssest({ name: "eddiespin" }), tag: "eddiespin" },
  { image: gifAssest({ name: "eekum" }), tag: "eekum" },
  { image: gifAssest({ name: "flappers" }), tag: "flappers" },
  { image: gifAssest({ name: "fubaldi" }), tag: "fubaldi" },
  { image: gifAssest({ name: "gwakgwak" }), tag: "gwakgwak" },

  { image: gifAssest({ name: "guitartime" }), tag: "guitartime" },
  { image: gifAssest({ name: "humpers" }), tag: "humpers" },
  { image: gifAssest({ name: "hypernodders" }), tag: "hypernodders" },
  { image: gifAssest({ name: "hypernopers" }), tag: "hypernopers" },
  { image: gifAssest({ name: "hyperpeepod" }), tag: "hyperpeepod" },
  { image: gifAssest({ name: "johnsouls" }), tag: "johnsouls" },

  { image: gifAssest({ name: "kissabrother" }), tag: "kissabrother" },
  { image: gifAssest({ name: "kissapregomie" }), tag: "kissapregomie" },
  { image: gifAssest({ name: "komodochomp" }), tag: "komodochomp" },
  { image: gifAssest({ name: "Igiggle" }), tag: "Igiggle" },
  { image: gifAssest({ name: "mariorun" }), tag: "mariorun" },
  { image: gifAssest({ name: "moon2bass" }), tag: "moon2bass" },
  { image: gifAssest({ name: "noted" }), tag: "noted" },
  { image: gifAssest({ name: "peepeegachat" }), tag: "peepeegachat" },
  { image: gifAssest({ name: "peepees" }), tag: "peepees" },
  { image: emoteAsset({ name: "shoopdawhoop" }), tag: "shoopdawhoop" },
  { image: emoteAsset({ name: "sosgame" }), tag: "sosgame" },
  { image: emoteAsset({ name: "sqshy" }), tag: "sqshy" },
  { image: emoteAsset({ name: "taxibro" }), tag: "taxibro" },
  { image: emoteAsset({ name: "tehpolecat" }), tag: "tehpolecat" },
  { image: gifAssest({ name: "peepersd" }), tag: "peepersd" },
  { image: gifAssest({ name: "peepoboom" }), tag: "peepoboom" },
  { image: gifAssest({ name: "peepocheering" }), tag: "peepocheering" },
  { image: gifAssest({ name: "peepogolfclap" }), tag: "peepogolfclap" },
  { image: gifAssest({ name: "peeponarusprint" }), tag: "peeponarusprint" },
  { image: gifAssest({ name: "peeposhy" }), tag: "peeposhy" },
  { image: gifAssest({ name: "peeposteer" }), tag: "peeposteer" },
  { image: emoteAsset({ name: "feelssnowman" }), tag: "feelsnowman" },
  { image: emoteAsset({ name: "feelssnowyman" }), tag: "feelsnowyman" },
  { image: emoteAsset({ name: "firespeed" }), tag: "firespeed" },
  { image: emoteAsset({ name: "fishmoley" }), tag: "fishmoley" },
  { image: emoteAsset({ name: "foreveralone" }), tag: "foreveralone" },

  { image: emoteAsset({ name: "monkas" }), tag: "monkas" },
  { image: emoteAsset({ name: "nam" }), tag: "nam" },
  { image: gifAssest({ name: "pepelepsy" }), tag: "pepelepsy" },
  { image: gifAssest({ name: "pepemetal" }), tag: "pepemetal" },
  { image: gifAssest({ name: "petthebaldie" }), tag: "petthebaldie" },
  { image: gifAssest({ name: "pettheheedie" }), tag: "pettheheedie" },
  { image: gifAssest({ name: "pettheqynoa" }), tag: "pettheqynoa" },
  { image: gifAssest({ name: "pukers" }), tag: "pukers" },
  { image: gifAssest({ name: "qynoalurks" }), tag: "qynoalurks" },
  { image: gifAssest({ name: "raremoon" }), tag: "raremoon" },
  { image: emoteAsset({ name: "gaben" }), tag: "gaben" },
  { image: emoteAsset({ name: "hahaa" }), tag: "hahaa" },
  { image: emoteAsset({ name: "hailhelix" }), tag: "hailhelix" },
  { image: emoteAsset({ name: "icecold" }), tag: "icecold" },

  { image: gifAssest({ name: "refracting" }), tag: "refracting" },
  { image: gifAssest({ name: "robpls" }), tag: "robpls" },
  { image: gifAssest({ name: "shruggers" }), tag: "shruggers" },
  { image: gifAssest({ name: "shushers" }), tag: "shushers" },
  { image: gifAssest({ name: "slap" }), tag: "slap" },
  { image: gifAssest({ name: "sneakers" }), tag: "sneakers" },
  { image: emoteAsset({ name: "cvhazmat" }), tag: "cvhazmat" },
  { image: emoteAsset({ name: "cvl" }), tag: "cvl" },
  { image: emoteAsset({ name: "cvr" }), tag: "cvr" },
  { image: emoteAsset({ name: "cvmask" }), tag: "cvmask" },
  { image: emoteAsset({ name: "datsauce" }), tag: "datsauce" },
  { image: emoteAsset({ name: "dogchamp" }), tag: "dogchamp" },
  { image: emoteAsset({ name: "duckerz" }), tag: "duckerz" },
  { image: emoteAsset({ name: "feelsamazingman" }), tag: "feelsamazingman" },
  { image: emoteAsset({ name: "feelsbadman" }), tag: "feelsbadman" },
  { image: emoteAsset({ name: "feelsbirthdayman" }), tag: "feelsbirthdayman" },
  { image: emoteAsset({ name: "feelsgoodman" }), tag: "feelsgoodman" },
  { image: gifAssest({ name: "solarflare" }), tag: "solarflare" },
  { image: gifAssest({ name: "soulshroom" }), tag: "soulshroom" },
  { image: gifAssest({ name: "speeders" }), tag: "speeders" },
  { image: gifAssest({ name: "tanties" }), tag: "tanties" },
  { image: gifAssest({ name: "teatime" }), tag: "teatime" },
  { image: emoteAsset({ name: "angelthump" }), tag: "angelthump" },
  { image: emoteAsset({ name: "ariw" }), tag: "ariw" },
  { image: emoteAsset({ name: "brobalt" }), tag: "brobalt" },
  { image: emoteAsset({ name: "bttvnice" }), tag: "bttvnice" },
  { image: emoteAsset({ name: "burself" }), tag: "burself" },
  { image: emoteAsset({ name: "candianrage" }), tag: "candianrage" },
  { image: emoteAsset({ name: "cigrip" }), tag: "cigrip" },
  { image: emoteAsset({ name: "concerndoge" }), tag: "concerndoge" },
  { image: emoteAsset({ name: "cruw" }), tag: "cruw" },
  { image: gifAssest({ name: "teatime2" }), tag: "teatime2" },
  { image: gifAssest({ name: "tinyteeth" }), tag: "tinyteeth" },
  { image: gifAssest({ name: "twerkers" }), tag: "twerkers" },
  { image: gifAssest({ name: "vanish" }), tag: "vanish" },
  { image: gifAssest({ name: "vibers" }), tag: "vibers" },
  { image: emoteAsset({ name: "twat" }), tag: "twat" },
  { image: emoteAsset({ name: "vapenation" }), tag: "vapenation" },
  { image: emoteAsset({ name: "vislaud" }), tag: "vislaud" },
  { image: emoteAsset({ name: "watchusay" }), tag: "watchusay" },
  { image: emoteAsset({ name: "wowee" }), tag: "wowee" },
  { image: emoteAsset({ name: "wubtf" }), tag: "wubtf" },
  { image: gifAssest({ name: "wowers" }), tag: "wowers" },
  { image: gifAssest({ name: "yappp" }), tag: "yappp" },

  // emotes
];
