name: Sync main with develop via a PR
on:
  push:
    branches:
      - develop
jobs:
  syncMainWithDevelop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Reset develop branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: main-sync-with-develop
          reviewers: vishalnarkhede, madsroskar, khushal87, santhoshvai, vanGalilea
          title: Sync main with develop
          body: This automated PR is to keep our main branch updated with develop as soon as possible. Any change to main branch is deployed as a new app in testflight and firebase. And it is accessible to the public.
          delete-branch: true
